package:
  name: py3-oslo-context
  description: Oslo Context library
  version: 6.0.0
  epoch: 1
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openstack/oslo.context
      tag: ${{package.version}}
      expected-commit: 589a7602b6828d20297283a7c1db7f08233c82fe
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
