package:
  name: py3-os-service-types
  description: Python library for consuming OpenStack sevice-types-authority data
  version: 1.8.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0
    runtime:
      - py3-pbr

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-pbr
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openstack/os-service-types
      tag: ${{package.version}}
      expected-commit: 5fc3a449b2be4a63209cf97a3e4cf7ec9b3981a0
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: os_service_types
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
