package:
  name: py3-os-traits
  description: A library containing standardized trait strings
  version: 3.5.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openstack/os-traits
      tag: ${{package.version}}
      expected-commit: d5e4e7e04ace709149727b94aae194b1ed9f1c0e
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
