package:
  name: py3-oslo-utils
  description: Oslo Utility library
  version: 7.3.0
  epoch: 1
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0
    runtime:
      - py3-iso8601
      - py3-netaddr
      - py3-netifaces
      - py3-yaml
      - py3-tz

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openstack/oslo.utils
      tag: ${{package.version}}
      expected-commit: c5d589f2c266dfcd0900e09ea76394f3be457d16
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
