package:
  name: py3-eventlet
  description: Highly concurrent networking library
  version: 0.36.1
  epoch: 1
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eventlet/eventlet
      tag: ${{package.version}}
      expected-commit: 43edc1fe0fb2559b8285f150f52a0c1f1b0a8881
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
