package:
  name: py3-oslo-policy
  description: Oslo Policy library
  version: 4.6.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0
    runtime:
      - py3-oslo-config
      - py3-oslo-context
      - py3-oslo-serialization
      - py3-oslo-utils
      - py3-yaml
      - py3-requests
      - py3-stevedore

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openstack/oslo.policy
      tag: ${{package.version}}
      expected-commit: 4dccbc7085b8acd05e3f262dde459c7b00e9d8b9
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
