package:
  name: py3-oslo-messaging
  description: Oslo Messaging API
  version: 14.9.1
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0
    runtime:
      - py3-amqp
      - py3-cachetools
      - py3-futurist
      - py3-kombu
      - py3-oslo-config
      - py3-oslo-context
      - py3-oslo-log
      - py3-oslo-metrics
      - py3-oslo-middleware
      - py3-oslo-serialization
      - py3-oslo-service
      - py3-oslo-utils
      - py3-yaml
      - py3-stevedore
      - py3-webob

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openstack/oslo.messaging
      tag: ${{package.version}}
      expected-commit: 3803f1527416542e27dfc6f012fdc3cb127d1195
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
