package:
  name: py3-pint
  description: Physical quantities module
  version: 0.25
  epoch: 1
  target-architecture:
    - all
  copyright:
    - license: BSD
  dependencies:
    provider-priority: 0

vars:
  pypi-package: Pint
  import: Pint

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "313"

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hgrecco/pint
      tag: ${{package.version}}
      expected-commit: 20e3dd37ac46acae0fd7aaef144869acf03c4787

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: python/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
