package:
  name: py3-pint
  description: Physical quantities module
  version: 0.25
  epoch: 1
  copyright:
    - license: BSD-2-Clause
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - busybox
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3
  environment:
    SOURCE_DATE_EPOCH: "315532800" # 1980-01-01

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hgrecco/pint
      tag: ${{package.version}}
      expected-commit: 20e3dd37ac46acae0fd7aaef144869acf03c4787
  - uses: python/build-wheel
  - uses: strip

var-transforms:
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: import

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
