package:
  name: py3-ironic-python-agent
  description: OpenStack Bare Metal Provisioning Agent
  version: 11.1.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0
    runtime:
      - py3-pbr
      - py3-oslo-config
      - py3-oslo-concurrency
      - py3-oslo-log
      - py3-oslo-utils
      - py3-pint
      - py3-psutil
      - py3-udev
      - py3-requests
      - py3-stevedore
      - py3-tenacity
      - py3-werkzeug
      - py3-cryptography
      - py3-tooz
      - py3-zeroconf
      - py3-cheroot

var-transforms:
  - from: ${{package.name}}
    match: ^py3-([a-z]).+$
    replace: $1
    to: prefix
  - from: ${{package.name}}
    match: ^py3-(.+)$
    replace: $1
    to: package
  - from: ${{vars.package}}
    match: "-"
    replace: "_"
    to: import

environment:
  contents:
    packages:
      - busybox
      - wget
      - ca-certificates-bundle
      - python3
      - py3-pip

pipeline:
  - runs: |
      wget -T5 --tries=5 https://files.pythonhosted.org/packages/py3/${{vars.prefix}}/${{vars.package}}/${{vars.import}}-${{package.version}}-py3-none-any.whl
      pip install --no-deps --no-cache-dir --prefix=/usr --root=${{targets.destdir}} ${{vars.import}}-${{package.version}}-py3-none-any.whl

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
