package:
  name: uwsgi
  description: uWSGI application server container
  version: 2.0.28
  epoch: 0
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - jansson-dev
      - libcap-dev
      - libxml2-dev
      - openssl-dev
      - pcre2-dev
      - python3-dev
      - yaml-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/unbit/uwsgi
      tag: ${{package.version}}
      expected-commit: 02a2fc47c7cd32a5c0d1e07808f36cbe1533ecbe
  - runs: mv uwsgi/config.ini buildconf/wolfi.ini
  - runs: |
      cat <<EOF >> buildconf/wolfi.ini
      append_version = r${{package.epoch}}
      EOF

subpackages:
  - name: uwsgi-core
    description: core package for uwsgi
    pipeline:
      - runs: python3 uwsgiconfig.py --build wolfi
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv uwsgi ${{targets.subpkgdir}}/usr/bin/uwsgi
      - uses: strip

  - name: uwsgi-plugin-python3
    description: python3 plugin of uwsgi
    dependencies:
      runtime:
        - uwsgi-core
    pipeline:
      - runs: python3 uwsgiconfig.py --plugin plugins/python wolfi python3
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/uwsgi
          mv python3_plugin.so ${{targets.subpkgdir}}/usr/lib/uwsgi/python3_plugin.so
      - uses: strip
