#!/usr/bin/env python3
"""Generate the updatecli manifest that tracks every py3-*.yaml at its latest
PyPI release.

The manifest has one source + target per melange config, keyed by the config
filename stem (e.g. ``py3-requests``). The source is the PyPI project — its
name is derived from the melange package name (dropping the ``py3-`` prefix),
which PyPI resolves under PEP 503 normalization (``oslo-config`` ==
``oslo.config``). The target rewrites ``package.version`` in the melange YAML.

Run ``python3 scripts/gen-updatecli.py`` to regenerate
``updatecli/updatecli.d/pypi.yaml`` after adding or removing packages.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# melange stem (with the py3- prefix) -> PyPI project name. Only needed when
# the derived name does not resolve on PyPI; every current package resolves
# via normalization, so this is empty.
PYPI_NAME_OVERRIDES: dict[str, str] = {}

HEADER = "# GENERATED by scripts/gen-updatecli.py — do not edit by hand.\n"


def pypi_name(stem: str) -> str:
    if stem in PYPI_NAME_OVERRIDES:
        return PYPI_NAME_OVERRIDES[stem]
    return stem[len("py3-"):] if stem.startswith("py3-") else stem


def main() -> int:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    out = root / "updatecli" / "updatecli.d" / "pypi.yaml"

    sources: dict[str, dict] = {}
    targets: dict[str, dict] = {}
    for path in sorted(root.glob("py3-*.yaml")):
        try:
            doc = yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            print(f"warning: skipping {path.name}: {exc}", file=sys.stderr)
            continue
        if not isinstance(doc, dict) or "package" not in doc:
            continue

        stem = path.stem  # py3-requests
        pypi = pypi_name(stem)
        sources[stem] = {
            "name": f"Latest {pypi} release on PyPI",
            "kind": "pypi",
            "spec": {"name": pypi},
        }
        targets[stem] = {
            "name": f"{stem}: set package.version to the latest PyPI release",
            "kind": "yaml",
            "sourceid": stem,
            "spec": {"file": path.name, "key": "$.package.version"},
        }

    manifest = {
        "name": "Track py3-* package versions from PyPI",
        "sources": sources,
        "targets": targets,
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(HEADER + yaml.safe_dump(manifest, sort_keys=False, default_flow_style=False))
    print(f"wrote {out} ({len(sources)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
